spring:
  datasource:
    url: jdbc:h2:mem:point
    driver-class-name: org.h2.Driver
    username: sa
    password:

  h2:
    console:
      enabled: true
      path: /h2-console

  jpa:
    hibernate:
      ddl-auto: create
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.H2Dialect
    defer-datasource-initialization: true

  sql:
    init:
      mode: always

  data:
    redis:
      host: localhost
      port: 6379
